[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "conf.settings"
addopts =" --cov=. --cov-report=term-missing:skip-covered  --cov-fail-under=90 --verbose"
# to find your tests
python_files = ["tests.py", "test_*.py", "*_tests.py"]