name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile

      - name: Inspect
        run: docker-compose run  --rm wep pytest