name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker-compose build

      - name: Test
        run: docker-compose run web pytest